version: '3'
services:
  api-server:
    build:
      context: ./api-server
      dockerfile: ./Dockerfile
    working_dir: /app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@postgresql:5432
      - JWT_SECRET=secret
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/api-server/attachments:/app/attachments
      - /app/node_modules
      - /app/.pnpm-store

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_GRAPHQL_ENTRYPOINT: "http://localhost:3000/graphql"
    working_dir: /app
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - /app/.pnpm-store
