version: '3'
services:
  api-server:
    build:
      context: ./api-server
      dockerfile: ./Dockerfile
    working_dir: /app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgresql:5432
      - JWT_SECRET=secret
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/api-server/:/app
      - ${PWD}/api-server/attachments:/app/attachments
      - /app/node_modules
      - /app/.pnpm-store

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    working_dir: /app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GRAPHQL_ENTRYPOINT=http://api-server:3000/graphql
    ports:
      - "4000:4000"
    volumes:
      - ${PWD}/web/:/app
      - /app/node_modules
      - /app/.pnpm-store
