version: '3'
services:
  api-server:
    image: gplane/pnpm:8.14-node20
    working_dir: /app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgresql:5432
      - JWT_SECRET=secret
    ports:
      - "3000:3000"
    volumes:
      - ./api-server/:/app
      - /app/node_modules
      - /app/.pnpm-store
    command:
      - /bin/sh
      - -c
      - |
        pnpm install
        pnpm generate:prisma
        pnpm start:dev

  web:
    image: gplane/pnpm:8.14-node20
    working_dir: /app
    environment:
      - NODE_ENV=development
      - API_ENTRYPOINT=http://api-server:3000/graphql
    ports:
      - "4000:3000"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.pnpm-store
    command:
      - /bin/sh
      - -c
      - |
        pnpm install
        pnpm start
