version: '3'
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/db:/var/lib/postgresql/data
